### Inspiration: https://rpubs.com/cheevahagadog/hw

In [1]:
import pandas as pd
import numpy as np

In [2]:
nrows = 5000

In [3]:
np.random.seed(42)
np.random.binomial(n=1, p=0.5, size=20)

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0])

In [4]:
def create_impressions_skewed_distribution(size=25):
    pers = range(0, 10)
    # need to parameterize this
    prob=[30.0]*(len(pers)-9) + [5.0]*2 + [1.0]*7
    prob /= np.sum(prob)
    skewed_array = np.random.choice(pers, replace=True, size=size, p=prob)
    return skewed_array

In [5]:
def create_clicks_skewed_distribution(size=25):
    pers = range(0, 6)
    # need to parameterize this
    prob=[30.0]*(len(pers)-3) + [5.0]*2 + [1.0]*1
    prob /= np.sum(prob)
    skewed_array = np.random.choice(pers, replace=True, size=size, p=prob)
    return skewed_array

In [6]:
def create_day_dist(size):
    # semi-even
    prob = [1.0]*4 + [3.0]*23 + [1.0]*4
    prob /= np.sum(prob)
    return np.random.choice(31, size=size, p=prob)

In [7]:
np.random.seed(42)
df = pd.DataFrame({ 'Age' : [int(i) for i in np.random.normal(loc=35, scale=15, size=nrows)],
                    'Gender' : np.random.binomial(n=1, p=0.4, size=nrows),
                    'Impressions' : create_impressions_skewed_distribution(size=nrows),
                    'Clicks' : create_clicks_skewed_distribution(size=nrows),
                    'Signed_In' : np.random.binomial(n=1, p=0.35, size=nrows),
                    'Day' : create_day_dist(size=nrows)})

In [8]:
df

      Age  Clicks  Day  Gender  Impressions  Signed_In
0      42       1   24       0            0          1
1      32       1    8       0            0          0
2      44       1   18       0            3          0
3      57       1   24       0            0          0
4      31       0   13       0            0          0
5      31       2   26       1            0          0
6      58       2   25       1            0          0
7      46       2    8       1            3          0
8      27       1    9       0            0          0
9      43       1    7       0            7          0
10     28       1    7       0            7          1
11     28       0   25       1            0          1
12     38       1   26       0            0          1
13      6       0    3       1            3          0
14      9       0   17       0            0          0
15     26       2   17       0            0          1
16     19       0   12       0            0          1
17     39       4   18       0            0          0
18     21       1   26       1            2          0
19     13       4    7       1            0          0
20     56       0    5       0            0          1
21     31       1    2       0            6          0
22     36       1   12       1            2          0
23     13       2   11       1            0          1
24     26       1   13       0            2          0
25     36       0   15       0            0          0
26     17       2   22       0            2          0
27     40       1   12       0            0          0
28     25       0   11       0            0          0
29     30       1   23       0            1          0
...   ...     ...  ...     ...          ...        ...
4970   57       0   10       1            0          0
4971   33       0   13       0            0          1
4972   19       4   18       1            0          0
4973    3       2   15       0            0          1
4974   12       1   24       0            0          0
4975   14       2   25       0            5          0
4976   55       4   14       0            0          1
4977   36       2    8       1            0          0
4978   40       2   26       1            0          1
4979    1       2   21       1            0          1
4980   17       0   19       1            0          0
4981   48       0   21       0            1          0
4982   39       2    4       0            0          1
4983   32       1    4       1            0          1
4984   43       0    6       1            4          0
4985   59       1    6       0            5          0
4986   31       1   13       0            8          0
4987   36       4    6       0            2          0
4988   37       2   24       1            5          1
4989   70       1   17       0            0          0
4990    3       4   12       0            0          0
4991   45       3    4       0            0          0
4992   33       1   17       1            1          0
4993   43       3    5       0            7          0
4994   25       1   21       1            0          0
4995   34       0   23       0            0          0
4996   45       0   16       1            2          0
4997   81       2    6       1            6          0
4998   47       1   22       0            1          0
4999   22       2   10       0            8          1

[5000 rows x 6 columns]

In [9]:
df.to_csv("clouseau_data.csv", index=False)

### Starting the challenge!
* Open up a new Jupyter Notebook using the command line
* Read in the CSV file (using Pandas or CSV reader)

### Task 0:
Some of this age data doesn't make sense, there must have been an error in it. Filter out all the rows where the age is equal to zero. How many rows were removed?

In [10]:
df = df[df['Age'] > 0]

### Task 1
Create a new variable, age_group, that categorizes users as “<18”, “18-24”, “25-34”, “35-44”, “45-54”, “55-64” and “65+”.

In [11]:
bins = [0, 18, 25, 35, 45, 55, 65, 100]
group_names = ["<18", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"]
df['age_group'] = pd.cut(df.Age, bins, labels=group_names)

/opt/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [12]:
pd.value_counts(df['age_group'])

35-44    1265
25-34    1240
45-54     733
18-24     657
<18       646
55-64     310
65+        94
Name: age_group, dtype: int64

### Task 2
For a single day,
Plot the distributions of number of impressions and click-through-rate

In [13]:
df

      Age  Clicks  Day  Gender  Impressions  Signed_In age_group
0      42       1   24       0            0          1     35-44
1      32       1    8       0            0          0     25-34
2      44       1   18       0            3          0     35-44
3      57       1   24       0            0          0     55-64
4      31       0   13       0            0          0     25-34
5      31       2   26       1            0          0     25-34
6      58       2   25       1            0          0     55-64
7      46       2    8       1            3          0     45-54
8      27       1    9       0            0          0     25-34
9      43       1    7       0            7          0     35-44
10     28       1    7       0            7          1     25-34
11     28       0   25       1            0          1     25-34
12     38       1   26       0            0          1     35-44
13      6       0    3       1            3          0       <18
14      9       0   17       0            0          0       <18
15     26       2   17       0            0          1     25-34
16     19       0   12       0            0          1     18-24
17     39       4   18       0            0          0     35-44
18     21       1   26       1            2          0     18-24
19     13       4    7       1            0          0       <18
20     56       0    5       0            0          1     55-64
21     31       1    2       0            6          0     25-34
22     36       1   12       1            2          0     35-44
23     13       2   11       1            0          1       <18
24     26       1   13       0            2          0     25-34
25     36       0   15       0            0          0     35-44
26     17       2   22       0            2          0       <18
27     40       1   12       0            0          0     35-44
28     25       0   11       0            0          0     18-24
29     30       1   23       0            1          0     25-34
...   ...     ...  ...     ...          ...        ...       ...
4970   57       0   10       1            0          0     55-64
4971   33       0   13       0            0          1     25-34
4972   19       4   18       1            0          0     18-24
4973    3       2   15       0            0          1       <18
4974   12       1   24       0            0          0       <18
4975   14       2   25       0            5          0       <18
4976   55       4   14       0            0          1     45-54
4977   36       2    8       1            0          0     35-44
4978   40       2   26       1            0          1     35-44
4979    1       2   21       1            0          1       <18
4980   17       0   19       1            0          0       <18
4981   48       0   21       0            1          0     45-54
4982   39       2    4       0            0          1     35-44
4983   32       1    4       1            0          1     25-34
4984   43       0    6       1            4          0     35-44
4985   59       1    6       0            5          0     55-64
4986   31       1   13       0            8          0     25-34
4987   36       4    6       0            2          0     35-44
4988   37       2   24       1            5          1     35-44
4989   70       1   17       0            0          0       65+
4990    3       4   12       0            0          0       <18
4991   45       3    4       0            0          0     35-44
4992   33       1   17       1            1          0     25-34
4993   43       3    5       0            7          0     35-44
4994   25       1   21       1            0          0     18-24
4995   34       0   23       0            0          0     25-34
4996   45       0   16       1            2          0     35-44
4997   81       2    6       1            6          0       65+
4998   47       1   22       0            1          0     45-54
4999   22       2   10       0            8          1     18-24

[4945 rows x 7 columns]

### Task 3
Define a new variable to segment or categorize users based on their click behavior

### Task 4
Explore the data and make visual and quantitative comparisons across user segments / demographics

### Task 5
Create metrics/measurements/statistics that summarize the data

### Task 6 
Now extend your analysis across days. Visualize metrics and distributions over time

### Task 7
Describe and interpret any patterns you find